services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        container_name: laravel_app
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./public:/var/www/html/public
        environment:
            APP_ENV: production
            APP_KEY: base64:OzVtJqHCBu9BvFuR/KT3if20sERvdm+bP8qEi8msRW4=
            APP_DEBUG: false
            DB_CONNECTION: sqlite
            DB_DATABASE: /var/www/html/database/database.sqlite
        depends_on:
            - db

    db:
        image: nouchka/sqlite3
        container_name: sqlite_db
        volumes:
            - ./database:/root/db
        command: "tail -f /dev/null"
